version: "3.9"
services:
  db:
    image: postgres:15-alpine
    container_name: orchestrator_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orchestrator
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: orchestrator_app
    environment:
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_MODEL=${LLM_MODEL:-gpt-4o-mini}
      - TOOL_CLIENT_MODE=${TOOL_CLIENT_MODE:-mock}
      - NOTE_MAKER_URL=${NOTE_MAKER_URL:-http://note-maker:8080/api/notes}
      - FLASHCARD_URL=${FLASHCARD_URL:-http://flashcards:8080/api/cards}
      - CONCEPT_EXPLAINER_URL=${CONCEPT_EXPLAINER_URL:-http://concept-explainer:8080/api/explain}
      - DATABASE_URL=${DATABASE_URL:-postgresql+psycopg2://postgres:postgres@db:5432/orchestrator}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
